# Generated by Django 5.1.6 on 2025-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_availabilityslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareCRMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
            ],
        ),
    ]
