# Generated by Django 5.1.6 on 2025-05-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_childcarecrmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='end_datetime_raw',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='start_datetime_raw',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
